src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 13)]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'integer')]
    private $nombre_pages;

    #[ORM\Column(type: 'date')]
    private $date_de_parution;

    #[ORM\Column(type: 'integer')]
    private $note;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $Genres;

    #[ORM\ManyToMany(targetEntity: Auteur::class, inversedBy: 'livres')]
    private $Auteurs;

    public function __construct()
    {
        $this->Genres = new ArrayCollection();
        $this->Auteurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }
    public function __toString()
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->Genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->Genres->contains($genre)) {
            $this->Genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->Genres->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->Auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->Auteurs->contains($auteur)) {
            $this->Auteurs[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->Auteurs->removeElement($auteur);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn',null,[
                'label' => false,
                'attr'=>[
                    'placeholder' => 'L\'ISBN',
                ],
            ])
            ->add('titre',null,[
                'label' => false,
                'attr'=>[
                    'placeholder' => 'Titre de l\'oeuvre',
                ]
            ])
            ->add('nombre_pages',null,[
                'label' => false,
                'attr'=>[
                    'placeholder' => 'Nombre de pages',
                    'min'=>1,
                    'max'=>10000
                ]
            ])
            ->add('date_de_parution',DateType::class,[
                'widget' => 'single_text',
                
                'label' => false,
            ])
            ->add('note',ChoiceType::class,[
                'label' => false,
                'choices' => [
                    '1/20'=>1,
                    '2/20'=>2,
                    '3/20'=>3,
                    '4/20'=>4,
                    '5/20'=>5,
                    '6/20'=>6,
                    '7/20'=>7,
                    '8/20'=>8,
                    '9/20'=>9,
                    '10/20'=>10,
                    '11/20'=>11,
                    '12/20'=>12,
                    '13/20'=>13,
                    '14/20'=>14,
                    '15/20'=>15,
                    '16/20'=>16,
                    '17/20'=>17,
                    '18/20'=>18,
                    '19/20'=>19,
                    '20/20'=>20,
                ]
            ])
            ->add('Genres',null,[
                'label' => false,
            ])
            ->add('Auteurs',null,[
                'label' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/livre')]
class LivreController extends AbstractController
{
    #[Route('/', name: 'livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository): Response
    {
        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/livre/_form.html.twig
{% if app.user and app.user.roles[0]=="ROLE_ADMIN"  %}
{{ form_start(form) }}
    <table class="table ">
        <tr>
            <th>ISBN</th>
            <td>
                {{ form_row(form.isbn) }}
            </td>
        </tr>
        <tr>
            <th>Titre</th>
            <td>
                {{ form_row(form.titre) }}
            </td>
        </tr>
        <tr>
            <th>Nombre de Pages</th>
            <td>
                {{ form_row(form.nombre_pages) }}
            </td>
        </tr>
        <tr>
            <th>Date de creation</th>
            <td>
                {{ form_row(form.date_de_parution) }}
            </td>
        </tr>
        <tr>
            <th>Note du livre</th>
            <td>
                {{ form_row(form.note) }}
            </td>
        </tr>
        <tr>
            <th>Genre</th>
            <td>
                {{ form_row(form.Genres) }}
            </td>
        </tr>
        <tr>
            <th>Author</th>
            <td>
                {{ form_row(form.Auteurs) }}
            </td>
        </tr>
    </table>
     <button class='btn btn-primary'>{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
   

{% endif %}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('livre_index') }}">back to list</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}

{% block body %}
    <div style="text-align:center">
    <h1 style="background-color:black;color:white;">Livres</h1>
  </div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Isbn</th>
                <th>Titre</th>
                <th>Nombre_pages</th>
                <th>Date_de_parution</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td>{{ livre.isbn }}</td>
                <td>{{ livre.titre }}</td>
                <td>{{ livre.nombrePages }}</td>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
                <td>{{ livre.note }}</td>
                <td>
                     <a class='btn btn-primary' href="{{path('livre_show', {'id': livre.id})  }}">Show</a>
                      {% if app.user and app.user.roles[0]=="ROLE_ADMIN"  %}
                    <a class='btn btn-primary' href="{{path('livre_edit',{'id' : livre.id})  }}">Edit</a>
                      {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if app.user and app.user.roles[0]=="ROLE_ADMIN"  %}
    <a class = 'btn btn-primary' href="{{ path('livre_new') }}">Create new</a>
     {% endif %}
    <a class = 'btn btn-secondary' href="{{ path('home') }}">go back</a>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('livre_index') }}">back to list</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <div style="text-align:center">
    <h1 style="background-color:black;color:white;">Livre</h1>
  </div>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th>Isbn</th>
                <td>{{ livre.isbn }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Nombre_pages</th>
                <td>{{ livre.nombrePages }}</td>
            </tr>
            <tr>
                <th>Date_de_parution</th>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ livre.note }}</td>
            </tr>
        </tbody>
    </table>

    <a class = 'btn btn-secondary' href="{{ path('livre_index') }}">back to list</a>
    {% if app.user and app.user.roles[0]=="ROLE_ADMIN"  %}

    <a class = 'btn btn-primary' href="{{ path('livre_edit', {'id': livre.id}) }}">edit</a>
     {% endif %}
 {% if app.user and app.user.roles[0]=="ROLE_ADMIN"  %}
 {{ include('livre/_delete_form.html.twig') }}
 {% endif %}
{% endblock %}